author:
  name: Greeshma Mathew
  email: "greeshma.mathew@gmail.com"
theme: minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/greeshma1196" }
    - {
        platform: linkedin,
        user_url: "https://www.linkedin.com/in/greeshma-mathew/",
      }
